application: zouk-event-calendar
version: 1
runtime: php55
api_version: 1

handlers:
- url: /.*
  script: index.php

# All URLs beginning with /stylesheets are treated as paths to static files in
# the stylesheets/ directory.
- url: /stylesheets
  static_dir: stylesheets
  mime_type: text/css

- url: /images
  static_dir: images

# Everything is uploaded unless following is used
#skip_files:
