application: zouk-event-calendar
version: 1
runtime: php55
api_version: 1

handlers:
# All URLs beginning with /stylesheets are treated as paths to static files in
# the stylesheets/ directory.
- url: /stylesheets
  static_dir: stylesheets
  mime_type: text/css

- url: /images
  static_dir: images

- url: /js
  static_dir: js

# for cron (login: admin, to prevent users from running the script)
- url: /tasks/searchfb
  script: trawl.php
  login: admin

# for ajax calls from client; if it asks for x.php then give it x.php and not index.html
- url: /token.php
  script: token.php

# like above
- url: /mail.php
  script: mail.php

# these are executed in order, so put this last
- url: /.*
  script: index.html

# facebook app id
# XXX just encode it directly in js file
# env_variables:
#  FACEBOOK_APP_ID: 1263842110297634

# Everything is uploaded unless following is used
#skip_files:
