application: zouk-event-calendar
version: 1
runtime: php55
api_version: 1

handlers:
# All URLs beginning with /stylesheets are treated as paths to static files in
# the stylesheets/ directory.
- url: /stylesheets
  static_dir: stylesheets
  mime_type: text/css

- url: /images
  static_dir: images

- url: /js
  static_dir: js

# these are executed in order, so put this last
- url: /.*
  script: index.php

# facebook app id
# XXX just encode it directly in js file
# env_variables:
#  FACEBOOK_APP_ID: 1263842110297634

# Everything is uploaded unless following is used
#skip_files:
